---
R1:
  hostname: "192.168.68.210"
  platform: "juniper_junos"
  username: "john"
  password: "Juniper1"
  groups:
    - juniper_group
  data:
    device_name: "R1"

R2:
  hostname: "192.168.68.211"
  platform: "juniper_junos"
  username: "john"
  password: "Juniper1"
  groups:
    - juniper_group
  data:
    device_name: "R1"


